import { updateUser } from '@api'
import * as toast from '@components/toast'
import { useAuthStore } from '@stores'
import { useCallback, useState } from 'react'

import { useUsernameValidation } from './useUsernameValidation'

export const useProfileUpdate = () => {
  const user = useAuthStore((state) => state.profile)
  const [loading, setLoading] = useState(false)
  const { validateUsername } = useUsernameValidation()

  const handleSave = useCallback(
    async ({ successToast }: { successToast?: string } = {}) => {
      if (!user) return
      setLoading(true)

      const { isValid, errorMessage } = await validateUsername(user?.username)
      if (!isValid) {
        if (errorMessage) {
          toast.Error(errorMessage)
        }
        setLoading(false)
        return
      }

      // Get fresh profile data from store
      const currentProfile = useAuthStore.getState().profile
      if (!currentProfile) {
        setLoading(false)
        return
      }

      // Build a clean payload without display_name (generated by backend)
      const { display_name: _displayName, ...profilePayload } = currentProfile

      try {
        const { error } = await updateUser(user.id, profilePayload)

        if (error) {
          console.error(error)
          toast.Error('Error updating profile!')
        } else {
          toast.Success(successToast || 'Profile updated successfully!')
        }
      } catch (error) {
        console.error(error)
        toast.Error('Error updating profile!')
      }

      setLoading(false)
    },
    [user, validateUsername]
  )

  return { loading, handleSave }
}
