import { updateUser } from '@api'
import * as toast from '@components/toast'
import { useAuthStore } from '@stores'
import { useCallback, useState } from 'react'

import { useUsernameValidation } from './useUsernameValidation'

interface SaveOptions {
  /** Custom success toast message */
  successToast?: string
  /** Skip username validation (e.g., when only links changed — avoids unnecessary API call) */
  skipUsernameValidation?: boolean
}

export const useProfileUpdate = () => {
  const user = useAuthStore((state) => state.profile)
  const [loading, setLoading] = useState(false)
  const { validateUsername } = useUsernameValidation()

  const handleSave = useCallback(
    async ({ successToast, skipUsernameValidation }: SaveOptions = {}) => {
      if (!user) return
      setLoading(true)

      try {
        // Validate username unless explicitly skipped (e.g., link-only save)
        if (!skipUsernameValidation) {
          const { isValid, errorMessage } = await validateUsername(user?.username)
          if (!isValid) {
            if (errorMessage) toast.Error(errorMessage)
            return
          }
        }

        // Get fresh profile data from store
        const currentProfile = useAuthStore.getState().profile
        if (!currentProfile) return

        // Build a clean payload without display_name (generated by backend)
        const { display_name: _displayName, ...profilePayload } = currentProfile

        const { error } = await updateUser(user.id, profilePayload)

        if (error) {
          console.error(error)
          toast.Error('Error updating profile!')
        } else {
          toast.Success(successToast || 'Profile updated successfully!')
        }
      } catch (error) {
        console.error(error)
        toast.Error('Error updating profile!')
      } finally {
        setLoading(false)
      }
    },
    [user, validateUsername]
  )

  return { loading, handleSave }
}
