module.exports = {
  apps : [
    {
      name: "master",
      script: "./node_modules/ep_etherpad-lite/node/server.js",
      env: {
        NODE_ENV: "production",
        PORT:"9001",
        DB_USER : `${process.env.DB_USER}`,
        DB_PASS : `${process.env.DB_PASS}`,
        DB_HOST : `${process.env.DB_HOST}`,
        DB_TYPE : `${process.env.DB_TYPE}`,
        DB_PORT : `${process.env.DB_PORT}`,
        DB_NAME : `${process.env.DB_NAME}`,
        SSL : `${process.env.SSL}`,
        BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
        ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
        ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
        MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
      },
    },
    {
    name: "dev",
    script: "./node_modules/ep_etherpad-lite/node/server.js",
    env: {
      NODE_ENV: "production",
      PORT:"9002",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
      ROCKET_CHAT_ADMIN_USERID : `${process.env.ROCKET_CHAT_ADMIN_USERID}`,
      ROCKET_CHAT_ADMIN_TOKEN : `${process.env.ROCKET_CHAT_ADMIN_TOKEN}`,

    },
  },
  {
    name: "dev-hossein",
    script: "./node_modules/ep_etherpad-lite/node/server.js",
    env: {
      NODE_ENV: "production",
      PORT:"9003",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
    },
  },
  {
    name: "dev-samir",
    script: "./node_modules/ep_etherpad-lite/node/server.js",
    env: {
      NODE_ENV: "production",
      PORT:"9004",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
    },
  },{
    name: "update",
    script: "./node_modules/ep_etherpad-lite/node/server.js",
    env: {
      NODE_ENV: "production",
      PORT:"9005",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      SSL : `${process.env.SSL}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
    },
  },
  
  {
    name: "test",
    script: "./node_modules/ep_etherpad-lite/node/server.js --experimental-worker",
    env: {
      NODE_ENV: "production",
      PORT:"9006",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      SSL : `${process.env.SSL}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
    },
  },
  {
    name: "vanilla",
    script: "./node_modules/ep_etherpad-lite/node/server.js",
    env: {
      NODE_ENV: "production",
      PORT:"9007",
      DB_USER : `${process.env.DB_USER}`,
      DB_PASS : `${process.env.DB_PASS}`,
      DB_HOST : `${process.env.DB_HOST}`,
      DB_TYPE : `${process.env.DB_TYPE}`,
      DB_PORT : `${process.env.DB_PORT}`,
      DB_NAME : `${process.env.DB_NAME}`,
      SSL : `${process.env.SSL}`,
      BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
      ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
      ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
      MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
    },
  }
  
  

]
}
