module.exports = {
  apps: [
    {
      name: "etherpad",
      script: "node_modules/ep_etherpad-lite/node/server.js",
      watch: false,
    },
    {
      name: "ws_main",
      script: "ws.router/server/index.pm2.cluster.js",
      instances: 1,
      watch: false,
      restart_delay: 30000,
      exec_mode: "cluster",
      env: {
        PORT: 3000,
        DB_USER : `${process.env.DB_USER}`,
        DB_PASS : `${process.env.DB_PASS}`,
        DB_HOST : `${process.env.DB_HOST}`,
        DB_TYPE : `${process.env.DB_TYPE}`,
        DB_PORT : `${process.env.DB_PORT}`,
        DB_NAME : `${process.env.DB_NAME}`,
        SSL : `${process.env.SSL}`,
        BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
        ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
        ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
        MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
        NODE_ENV: "production",

      },
    },
    {
      name: "ws_dev",
      script: "ws.router/server/index.pm2.cluster.js",
      instances: 1,
      watch: false,
      restart_delay: 30000,
      exec_mode: "cluster",
      env: {
        PORT: 8000,
        DB_USER : `${process.env.DB_USER}`,
        DB_PASS : `${process.env.DB_PASS}`,
        DB_HOST : `${process.env.DB_HOST}`,
        DB_TYPE : `${process.env.DB_TYPE}`,
        DB_PORT : `${process.env.DB_PORT}`,
        DB_NAME : `${process.env.DB_NAME}`,
        BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
        ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
        ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
        MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
        NODE_ENV: "production",

      },
    },
    {
      name: "ws_democracy",
      script: "ws.router/server/index.pm2.cluster.js",
      instances: 1,
      watch: false,
      restart_delay: 30000,
      exec_mode: "cluster",
      env: {
        PORT: 8001,
        max_memory_restart: '400M',
        watch: false,
        DB_USER : `${process.env.DB_USER}`,
        DB_PASS : `${process.env.DB_PASS}`,
        DB_HOST : `${process.env.DB_HOST}`,
        DB_TYPE : `${process.env.DB_TYPE}`,
        DB_PORT : `${process.env.DB_PORT}`,
        DB_NAME : `${process.env.DB_NAME}`,
        SSL : `${process.env.SSL}`,
        BUCKET_S3_SERVER : `${process.env.BUCKET_S3_SERVER}`,
        ACCESS_KEY_ID : `${process.env.ACCESS_KEY_ID}`,
        ACCESS_KEY_SECRET : `${process.env.ACCESS_KEY_SECRET}`,
        MEDIA_BUCKET_NAME : `${process.env.MEDIA_BUCKET_NAME}`,
        NODE_ENV: "production",

      },
    },
  ],
};
