version: "3.9"

services:
 redis:
  image: redis:alpine
  container_name: prod-redis-docsplus
  restart: unless-stopped

 backend:
  env_file: .env
  image: prod.docs.plus
  container_name: prod-back-docsplus
  restart: always
  build: .
  depends_on:
   - redis
  links:
   - redis
  environment:
   DATABASE_TYPE: ${DATABASE_TYPE:-SQLite}
   REDIS_HOST: redis
  ports:
   - '${EXPOSE_APP_PORT:-8003}:${APP_PORT}'
