version: "3.9"

services:
 redis-server:
  image: redis:alpine
  restart: unless-stopped

 backend:
  env_file: .env
  restart: always
  build: .
  depends_on:
   - redis-server
  links:
   - redis-server
  environment:
   DATABASE_TYPE: ${DATABASE_TYPE:-SQLite}
   REDIS_HOST: redis-server
  ports:
   - '${EXPOSE_APP_PORT:-8002}:${APP_PORT}'

volumes:
 database-data:
