version: "3.9"

services:
 redis:
  image: redis:alpine
  container_name: stage-redis-docsplus
  restart: unless-stopped

 backend:
  env_file: .env
  image: stage.docs.plus
  container_name: stage-back-docsplus
  restart: always
  build: .
  depends_on:
   - redis
  links:
   - redis
  environment:
   DATABASE_TYPE: ${DATABASE_TYPE:-SQLite}
   REDIS_HOST: redis
  ports:
   - '${EXPOSE_APP_PORT:-8002}:${APP_PORT}'
   - '127.0.0.1:${HOCUSPOCUS_PORT:-1234}:0.0.0.0:${HOCUSPOCUS_PORT:-1234}'
