#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lerna/nx build
echo "Running lerna build..."
if npm run build; then
    echo "Build successful. Proceeding with push."
else
    echo "Build failed. Push aborted."
    exit 1
fi
